export const airports: string[] = [
  "Adampur Airport",
  "Agatti Airport",
  "Agra Air Force Station",
  "Akola Airport",
  "Allahabad Airport",
  "Ambikapur Airport",
  "Aurangabad Airport",
  "Bagdogra International Airport – IXB",
  "Balurghat Airport",
  "Bathinda Airport",
  "Begumpet Airport",
  "Behala Airport",
  "Belgaum Airport",
  "Bellary Airport",
  "Bhavnagar Airport",
  "Bhuj Airport",
  "Biju Patnaik International Airport – BBI",
  "Bilaspur Airport",
  "Birsa Munda Airport",
  "Bokaro Airport",
  "Calicut International Airport – CCJ",
  "Chandigarh International Airport – IXC",
  "Chaudhary Charan Singh International Airport – LKO",
  "Chennai International Airport – MAA",
  "Chhatrapati Rajaram Maharaj Airport",
  "Chhatrapati Shivaji International Airport – BOM",
  "Cochin International Airport – COK",
  "Coimbatore International Airport – CJB",
  "Cooch Behar Airport",
  "Dabolim Airport – GOI",
  "Devi Ahilya Bai Holkar Airport – IDR",
  "Devi Ahilyabai Holkar Airport",
  "Dibrugarh Airport",
  "Dimapur Airport",
  "Diu Airport",
  "Dr. Babasaheb Ambedkar International Airport – NAG",
  "Gaya Airport",
  "Gorakhpur Airport",
  "Gulbarga Airport",
  "Gwalior Airport",
  "Hindon Airport",
  "Hisar Airport",
  "Hubli Airport",
  "Imphal International Airport – IMF",
  "Indira Gandhi International Airport",
  "Indira Gandhi International Airport – DEL",
  "Jabalpur Airport",
  "Jaipur International Airport – JAI",
  "Jaisalmer Airport",
  "Jakkur Airfield",
  "Jalgaon Airport",
  "Jammu Airport",
  "Jamnagar Airport",
  "Jay Prakash Narayan International Airport – PAT",
  "Jeypore Airport",
  "Jodhpur Airport",
  "Jolly Grant Airport",
  "Jorhat Airport",
  "Juhu Aerodrome",
  "Kadapa Airport",
  "Kandla Airport",
  "Kangra Airport",
  "Kannur International Airport – CNN",
  "Kanpur Airport",
  "Karnal Airport",
  "Kazi Nazrul Islam Airport",
  "Kempegowda International Airport – BLR",
  "Khajuraho Airport",
  "Kishangarh Airport",
  "Kollam Airport",
  "Kota Airport",
  "Kullu-Manali Airport",
  "Lal Bahadur Shastri International Airport – VNS",
  "Lengpui Airport",
  "Lilabari Airport",
  "Lokpriya Gopinath Bordoloi International Airport – GAU",
  "Madurai Airport – IXM",
  "Maharaja Bir Bikram Airport",
  "Maharana Pratap Airport",
  "Mangalore International Airport – IXE",
  "Mysore Airport",
  "Nadirgul Airport",
  "Naini Saini Airport",
  "Nal Airport",
  "Nashik Airport",
  "Netaji Subhas Chandra Bose International Airport – CCU",
  "Pakyong Airport",
  "Panagarh Airport",
  "Pantnagar Airport",
  "Pasighat Airport",
  "Pathankot Airport",
  "Patiala Airport",
  "Porbandar Airport",
  "Puducherry Airport",
  "Pune Airport – PNQ",
  "Raja Bhoj Airport",
  "Rajahmundry Airport",
  "Rajiv Gandhi International Airport- HYD",
  "Rajkot Airport",
  "Sahnewal Airport",
  "Salem Airport",
  "Sardar Vallabhbhai Patel International Airport – AMD",
  "Satna Airport",
  "Sheikhul Aalam International Airport – SXR",
  "Shillong Airport",
  "Shimla Airport",
  "Shirdi Airport",
  "Shri Guru Gobind Singh Ji Airport",
  "Silchar Airport",
  "Solapur Airport",
  "Sonari Airport",
  "Sri Guru Ram Dass Jee International Airport – ATQ",
  "Surat International Airport – STV",
  "Swami Vivekananda Airport",
  "Tezpur Airport",
  "Thiruvananthapuram International Airport – TRV",
  "Thoothukudi Airport",
  "Tiruchirappalli International Airport – TRZ",
  "Tirupati Airport",
  "Vadodara Airport",
  "Veer Savarkar International Airport",
  "Veer Surendra Sai Airport",
  "Vijayawada Airport",
  "Visakhapatnam International Airport – VTZ",
  "Yavatmal Airport",
];
